#!/usr/bin/python3

import pygame, os, sys

def genFrog(surf):
  print("Searching for frog...")
  frog = [-1, -1]
  for i in range(surf.get_width()):
    for j in range(surf.get_height()):
      if surf.get_at((i, j)) == (0, 255, 0):
        print("Found frog at (%i, %i)" % (i, surf.get_height() - j - 1))
        surf.set_at((i, j), (255, 255, 255))
        frog = [i, surf.get_height() - j - 1]
  if frog[0] < 0: raise ValueError("Can't find frog.")
  return frog

def genFlies(surf):
  print("Searching for flies...")
  out = []
  for i in range(surf.get_width()):
    for j in range(surf.get_height()):
      if surf.get_at((i, j)) == (160, 160, 160):
        print("Found fly at (%i, %i)" % (i, surf.get_height() - j - 1))
        surf.set_at((i, j), (255, 255, 255))
        out.append([i, surf.get_height() - j - 1])
  if len(out) < 0: raise ValueError("Can't find flies")
  return out

def genTerrain(surf, top):
  d = 0
  out = []
  for i in range(surf.get_width()):
    col, layer = [], -1
    color, lastColor = tuple(), tuple()
    for j in range(surf.get_height()):
      color = surf.get_at((i, surf.get_height() - j - 1))
      if j == 0 and colorToType(color) == 'E': raise ValueError("Bottom of level cannot be left open.")
      else:
        if lastColor != color:
          layer += 1
          col.append([0, colorToType(color)])
        col[layer][0] += 1
      lastColor = color
    print("Column %i is %s." % (i, col))
    out.append(col)
    if len(col) > d: d = len(col)
  print("Depth of level is %i" % d)
  if d % 2 == top:
    print("Modifying depth to %s the top." % ("cap" if top else "uncap"))
    d -= 1
  
  for i in range(surf.get_width()):
    while len(out[i]) < d: out[i].append((0, colorToType((255, 255, 255))))
    while len(out[i]) > d: out[i].pop(-1)
    for j in range(d - 1, -1, -1):
      if top and out[i][j][1] == colorToType((0, 0, 0)): out[i][j] = (0, colorToType((255, 255, 255)))
      elif not top and out[i][j][1] == colorToType((255, 255, 255)): out[i][j] = (0, colorToType((255, 255, 255)))
      else: break
  return out

def colorToType(color):
  if color == (0, 0, 0): return 'S'
  if color == (63, 63, 63): return 'B'
  if color == (255, 255, 255): return 'E'



if __name__ == "__main__":
  print("Creating level at %s" % sys.argv[1])
  os.chdir(sys.argv[1])
  
  pygame.init()
  
  t = pygame.image.load("template.png")
  
  out = genFrog(t)
  with open("frog.txt", "w") as f:
    f.write("%i %i\n" % (out[0], out[1]))
  
  out = genFlies(t)
  with open("flies.txt", "w") as f:
    f.write("%i\n" % len(out))
    for i in out:
      f.write("%i %i\n" % (i[0], i[1]))
  
  cap = input("Should the top of the level be capped with solid tiles? (y/n) ").lower().startswith("y")
  out = genTerrain(t, cap)
  with open("terrain.txt", "w") as f:
    f.write("%i\n%i\n%i\n" % (len(out), len(out[0]), int(cap)))
    for i in out:
      for j in i: f.write("%s%i " % (j[1], j[0]))
      f.write("\n")
  
  pygame.quit()